.PHONY: task_3 task_35, task_4 task_45 task_5 main

all: main

task_3:
	g++ 3.cpp -lGL -lGLU -lglfw -g -o 3.o
task_35:
	g++ 35.cpp -lGL -lGLU -lglfw -g -o 35.o
task_4:
	g++ 4.cpp -lGL -lGLU -lglfw -g -o 4.o
task_45:
	g++ 45.cpp -lGL -lGLU -lglfw -g -o 45.o
task_5:
	g++ 5.cpp -lGL -lGLU -lglfw -g -o 5.o
main: task_3 task_35 task_4 task_45 task_5
clean:
	rm 3.o 35.o 4.o 45.o 5.o -rf